addpath("utilities");
model_rank = 3;
m=4;
q=2*model_rank+m;

Oi = zeros(2, 2);
Ii = eye(2, 2);
  
  
theta = [1,2,3,4,5,6,7,8,9,10,11,12]';

[Aq_gen, Cq_gen] = vector_generate_aq_cq(theta, q, model_rank);

A1 = [1,2;7,8];
A2 = [3,4;9,10];
A3 = [5,6;11,12];
Aq = [...
        A1, A2, A3, Oi, Oi, Oi, Oi, Oi, Oi, Oi;  ...
        Ii, Oi, Oi, Oi, Oi, Oi, Oi, Oi, Oi, Oi;  ...
        Oi, Ii, Oi, Oi, Oi, Oi, Oi, Oi, Oi, Oi; ...
        Oi, Oi, Ii, Oi, Oi, Oi, Oi, Oi, Oi, Oi;  ...
        Oi, Oi, Oi, Ii, Oi, Oi, Oi, Oi, Oi, Oi;  ...
        Oi, Oi, Oi, Oi, Ii, Oi, Oi, Oi, Oi, Oi;  ...
        Oi, Oi, Oi, Oi, Oi, Ii, Oi, Oi, Oi, Oi;  ...
        Oi, Oi, Oi, Oi, Oi, Oi, Ii, Oi, Oi, Oi;  ...
        Oi, Oi, Oi, Oi, Oi, Oi, Oi, Ii, Oi, Oi;  ...
        Oi, Oi, Oi, Oi, Oi, Oi, Oi, Oi, Ii, Oi;  ...
     ];
     
Cq = [ Ii, Oi, Oi, Oi, Oi, Oi, Oi, Oi, Oi, Oi]';
     
display(sum(sum(Aq-Aq_gen)));
display(sum(sum(Cq-Cq_gen)));