function [Aq, Cq] = vector_generate_aq_cq(theta, q, model_rank) 
  Aq = [ ...
           zeros(2, 2*q);
           eye(2*(q-1),(2*q-1)), zeros(2*(q-1),1) ...
         ];
  Cq = [ eye(2,2), zeros(2, 2*(q-1))]';
  for i=1:2:2*model_rank
     Aq(1:2,i:i+1) = [...
                          theta( (i):(i+1) )'; ...
                          theta( (2*model_rank+i):(2*model_rank+i+1) )' ...
                         ];
  endfor
endfunction
