function [ total_alarms_ideal,...
           total_alarms_est,...
           energy_based_indicator,...
           similarity_based_indicator ] = dual_channel_quantity_test( noise,...
                                                                      detection_ideal,...
                                                                      detection_est)
  %printf("Quantity test for channel L\n");
  [ total_alarms_ideal_l,...
    total_alarms_est_l,...
    energy_based_indicator_l,...
    similarity_based_indicator_l ] = single_channel_quantity_test( noise(:,1),...
                                                                   detection_ideal(:,1),...
                                                                   detection_est(:,1));
  %printf("Quantity test for channel R\n");
  [ total_alarms_ideal_r,...
    total_alarms_est_r,...
    energy_based_indicator_r,...
    similarity_based_indicator_r ] = single_channel_quantity_test( noise(:,2),...
                                                                   detection_ideal(:,2),...
                                                                   detection_est(:,2));
  total_alarms_ideal = [total_alarms_ideal_l, total_alarms_ideal_r];
  total_alarms_est = [total_alarms_est_l, total_alarms_est_r];
  energy_based_indicator = [energy_based_indicator_l, energy_based_indicator_r];
  similarity_based_indicator = [similarity_based_indicator_l, similarity_based_indicator_r];
  
  print_quantity_test_result( total_alarms_ideal,...
                              total_alarms_est,...
                              energy_based_indicator,...
                              similarity_based_indicator);
endfunction