function [clear_signal_fb, detection_signal_fb] = SCL_BIDI_ImpulseNoiseReduction (input_signal)
  
  global model_rank SCL_MODE BIDI_MODE;
  
  %%% Forward analysis
  clear_signal_f = zeros(size(input_signal));
  detection_signal_f = zeros(size(input_signal));
  ewls_coefficients_estimate_f = zeros(model_rank, length(input_signal), 2);
  ewls_noise_variance_f = zeros(size(input_signal));

  [clear_signal_f(:,1), ...
   detection_signal_f(:,1), ~, ~, ...
   ewls_coefficients_estimate_f(:,:,1), ...
   ewls_noise_variance_f(:,1)] = SCL_ImpulseNoiseReduction(input_signal(:,1));
 
  [clear_signal_f(:,2), ...
   detection_signal_f(:,2), ~, ~, ...
   ewls_coefficients_estimate_f(:,:,2), ...
   ewls_noise_variance_f(:,2)] = SCL_ImpulseNoiseReduction(input_signal(:,2));

  %%% Backward analysis
  clear_signal_b = zeros(size(input_signal));
  detection_signal_b = zeros(size(input_signal));
  ewls_coefficients_estimate_b = zeros(model_rank, length(input_signal), 2);
  ewls_noise_variance_b = zeros(size(input_signal));

  [clear_signal_b(:,1), ...
   detection_signal_b(:,1), ~, ~, ...
   ewls_coefficients_estimate_b(:,:,1), ...
   ewls_noise_variance_b(:,1)] = SCL_ImpulseNoiseReduction(flip(input_signal(:,1)));
 
  [clear_signal_b(:,2), ...
   detection_signal_b(:,2), ~, ~, ...
   ewls_coefficients_estimate_b(:,:,2), ...
   ewls_noise_variance_b(:,2)] = SCL_ImpulseNoiseReduction(flip(input_signal(:,2)));
 
  clear_signal_b = flip(clear_signal_b,1);
  detection_signal_b = flip(detection_signal_b,1);
  ewls_coefficients_estimate_b = flip(ewls_coefficients_estimate_b,2);
  ewls_noise_variance_b = flip(ewls_noise_variance_b,1);
  detection_signal_fb = zeros(size(detection_signal_f));
  %{ 
  %%% Expanding alarms
  [detection_signal_f(:,1), detection_signal_b(:,1)] = expand_alarms(detection_signal_f(:,1), detection_signal_b(:,1));
  [detection_signal_f(:,2), detection_signal_b(:,2)] = expand_alarms(detection_signal_f(:,2), detection_signal_b(:,2));
  
  %%% Creating bidirectional alarm
  
  detection_signal_fb(:,1) = create_bidirectional_alarm(detection_signal_f(:,1), detection_signal_b(:,1));
  detection_signal_fb(:,2) = create_bidirectional_alarm(detection_signal_f(:,2), detection_signal_b(:,2));
  %}
  
  detection_signal_fb(:,1) = merge_alarms(detection_signal_f(:,1), detection_signal_b(:,1));
  detection_signal_fb(:,2) = merge_alarms(detection_signal_f(:,2), detection_signal_b(:,2));
  %%% Bidirectional interpolation
  
  clear_signal_fb = clear_signal_f;
  clear_signal_fb(:,1) = bidirectional_interpolation(detection_signal_fb(:,1), ...
                                                clear_signal_f(:,1), ...
                                                clear_signal_b(:,1), ...
                                                ewls_coefficients_estimate_f(:,:,1), ...
                                                ewls_coefficients_estimate_b(:,:,1), ...
                                                ewls_noise_variance_f(:,1), ...
                                                ewls_noise_variance_b(:,1));
                                                
  clear_signal_fb(:,2) = bidirectional_interpolation(detection_signal_fb(:,2), ...
                                                clear_signal_f(:,2), ...
                                                clear_signal_b(:,2), ...
                                                ewls_coefficients_estimate_f(:,:,2), ...
                                                ewls_coefficients_estimate_b(:,:,2), ...
                                                ewls_noise_variance_f(:,2), ...
                                                ewls_noise_variance_b(:,2));
                                                
endfunction
