function [clear_signal_fb, detection_signal_fb] = ...
  SCL_BIDI_ImpulseNoiseReduction (clear_signal_f, ...
                                  clear_signal_b, ...
                                  detection_signal_f, ...
                                  detection_signal_b, ...
                                  coefficients_f, ...
                                  coefficients_b, ...
                                  noise_variance_f, ...
                                  noise_variance_b)
   
  %%% Expanding alarms
  [detection_signal_f, detection_signal_b] = expand_alarms(detection_signal_f, detection_signal_b);

  %%% Creating bidirectional alarm
  detection_signal_fb = create_bidirectional_alarm(detection_signal_f, detection_signal_b);
  
  %%% Bidirectional interpolation
  clear_signal_fb = bidirectional_interpolation(detection_signal_fb, ...
                                                clear_signal_f, ...
                                                clear_signal_b, ...
                                                coefficients_f, ...
                                                coefficients_b, ...
                                                noise_variance_f, ...
                                                noise_variance_b);
endfunction
