function [output_prediction, prediction_error, prediction_noise_variance, f] = ...
          open_loop_detector_step (input_sample, ...
          coefficients, ...
          regression_vector, ...
          prediction_noise_variance, ...
          starting_noise_variance, ...
          k, ...
          f)
output_prediction = coefficients'*regression_vector;
prediction_error = input_sample - output_prediction;
[prediction_noise_variance, f] = stoica(prediction_noise_variance, ...
                                        starting_noise_variance, ...
                                        coefficients, ...
                                        k, ...
                                        f);
endfunction
